# Generated by Django 5.2.5 on 2025-09-05 10:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('idusuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('perfil', models.CharField(default='usuario', max_length=45)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Alergia',
            fields=[
                ('idalergia', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idcategoria', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaReceita',
            fields=[
                ('idcategoria_receita', models.AutoField(primary_key=True, serialize=False)),
                ('nome_categoria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('idingrediente', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('substituicoes_sugeridas', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('idforum', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=45)),
                ('enunciado', models.CharField(max_length=45)),
                ('data_inicio', models.CharField(max_length=45)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('idreceita', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=45)),
                ('modo_preparo', models.TextField(max_length=255)),
                ('ingredientes', models.TextField(max_length=255)),
                ('porcoes', models.IntegerField()),
                ('categoria_receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categoriareceita')),
            ],
        ),
        migrations.CreateModel(
            name='Topico',
            fields=[
                ('idtopico', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=45)),
                ('enunciado', models.CharField(max_length=45)),
                ('data_inicio', models.CharField(max_length=45)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categoria')),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.forum')),
            ],
        ),
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('idpostagem', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.TextField(max_length=255)),
                ('data_publicacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('topico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.topico')),
            ],
        ),
        migrations.CreateModel(
            name='AlergiaHasUsuario',
            fields=[
                ('idusuario_alergia', models.AutoField(primary_key=True, serialize=False)),
                ('alergia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.alergia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('alergia', 'usuario')},
            },
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('idfavorito', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.receita')),
            ],
            options={
                'unique_together': {('receita', 'usuario')},
            },
        ),
        migrations.CreateModel(
            name='ReceitaHasIngrediente',
            fields=[
                ('id_visualizar_ingrediente', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.CharField(max_length=45)),
                ('unidade', models.CharField(max_length=45)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ingrediente')),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.receita')),
            ],
            options={
                'unique_together': {('receita', 'ingrediente')},
            },
        ),
    ]
