# Generated by Django 5.2.5 on 2025-09-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='receitas/'),
        ),
        migrations.AddField(
            model_name='receita',
            name='tempo_preparo',
            field=models.IntegerField(default=0, help_text='Tempo em minutos'),
        ),
    ]
