# Generated by Django 5.2.7 on 2025-10-10 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_receita_imagem_receita_tempo_preparo'),
    ]

    operations = [
        migrations.AddField(
            model_name='topico',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
