# Generated by Django 5.2.7 on 2025-10-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_topico_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='enunciado',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='forum',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='topico',
            name='enunciado',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='topico',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
