# Generated by Django 5.2.7 on 2025-10-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_forum_enunciado_alter_forum_titulo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='categoria_receita',
        ),
        migrations.AddField(
            model_name='receita',
            name='categorias_receita',
            field=models.ManyToManyField(to='app.categoriareceita'),
        ),
    ]
