# Generated by Django 3.2.25 on 2025-10-31 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_receita_categoria_receita_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='dificuldade',
            field=models.CharField(choices=[('F', 'Fácil'), ('M', 'Médio'), ('D', 'Difícil')], default='F', help_text='Nível de dificuldade da receita', max_length=1),
        ),
        migrations.AlterField(
            model_name='receita',
            name='ingredientes',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='receita',
            name='modo_preparo',
            field=models.TextField(max_length=1000),
        ),
    ]
