# Generated by Django 3.2.25 on 2025-11-29 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_receita_usuario'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='receitahasingrediente',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='receitahasingrediente',
            name='ingrediente',
        ),
        migrations.RemoveField(
            model_name='receitahasingrediente',
            name='receita',
        ),
        migrations.DeleteModel(
            name='Ingrediente',
        ),
        migrations.DeleteModel(
            name='ReceitaHasIngrediente',
        ),
    ]
